### ISSUE TITLE
how to use the image?

### ISSUE THREAD

**Issue by MSandro** [micw/docker-lxc#1]
Hi, it sound interesting to have an LXC Container inside Docker.
But how can I use your image? Could you please give an example in your desciption.
Thanks.

**Comment by micw** [comment]
Sorry for responding quite late. The project is still in the state of a working prototype. Nevertheless I use it to run my archlinux remote desktop with it ;-)

If you run on kubernetes, I could post my helm chart. Otherwise here's a brief docker use instruction:

- image: micwy/lxc
- needs to be run in privileged mode
- LXC_BOX env variable must point to a vagrant-lxc container image (either one of the official or an URL. I only tested my own archlinux base box with -e LXC_BOX=https://github.com/micw/vagrant-lxc-archlinux/releases/download/0.0.4/archlinux.box)
- mount /data as volume, it will contain the inner system's root and lxc config

Edit: The official boxes comes with DHCP preconfigured. For debian-like systems my network-hook removes the this config so that the lxc container uses the network of the docker container. With this you can just expose any port of the lxc container the docker way (via -p).

**Comment by MSandro** [comment]
Thank you very much

**Comment by iuridiniz** [comment]
sample:
`docker run -e LXC_BOX=debian/jessie64 -p 4022:22 -d --privileged --rm --name myvagrantmachine micwy/lxc
`

wait until machine is up
`docker logs -f myvagrantmachine`

ssh it via vagrant
`docker exec -it myvagrantmachine /opt/vagrant/bin/vagrant ssh`

**Comment by micw** [comment]
I'm currently rewriting the whole project, the new README will contain examples and better docs. The old version will be available at docker tag v0.1.
